from __future__ import annotations

import logging
import re
import random
import os
from dataclasses import dataclass, field
from pathlib import Path
from io import BytesIO

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE_TYPE, PP_PLACEHOLDER, MSO_AUTO_SHAPE_TYPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

from md2deck.config import AppConfig
from md2deck.models import PipelineArtifacts, SlideBlueprint, VisualIntent, LayoutMetadata
from md2deck.stages.pptx_animations import add_slide_animations

logger = logging.getLogger(__name__)

# --- Standards ---
SW, SH = Inches(13.333), Inches(7.5)
FS_TITLE_COVER, FS_SUB_COVER = 40, 20
FS_TITLE_SLIDE, FS_BODY_SLIDE = 25, 10
GAP_TITLE_BODY = Pt(2)

@dataclass
class RenderStage:
    name: str = "render"
    theme: any = None
    _slide_margin: float = 0.5
    _assets_dir: Path = Path("assets")

    def run(self, config: AppConfig, artifacts: PipelineArtifacts) -> None:
        if artifacts.blueprint is None:
            return
        
        self.theme = artifacts.theme
        self._slide_margin = artifacts.theme.design_dna.get("margin", 0.5)
        
        new_pres = Presentation(str(config.master_pptx))
        # Clear existing slides
        for _ in range(len(new_pres.slides)):
            rId = new_pres.slides._sldIdLst[0].rId
            new_pres.part.drop_rel(rId)
            del new_pres.slides._sldIdLst[0]

        total = len(artifacts.blueprint.slides)
        for i, slide_bp in enumerate(artifacts.blueprint.slides):
            layout_idx = self._resolve_layout_index(slide_bp, i, total)
            layout = new_pres.slide_layouts[layout_idx]
            slide = new_pres.slides.add_slide(layout)
            
            # 1. Native Master Placeholders
            self._fill_native_placeholders(slide, slide_bp)
            
            # 2. Add Branding/Footer Icon
            self._add_footer_branding(slide)
            
            # 3. Dynamic Card Content
            self._render_dynamic_alternating_layout(slide, slide_bp, i, total)
            
            intent_val = slide_bp.visual_intent
            if hasattr(intent_val, "value"): intent_val = intent_val.value
            add_slide_animations(slide, intent_val, len(slide.shapes))

        new_pres.save(str(config.output_pptx))
        logger.info(f"Presentation saved to {config.output_pptx}")

    def _resolve_layout_index(self, bp: SlideBlueprint, idx: int, total: int) -> int:
        meta_map = self.theme.layouts_metadata
        if bp.visual_intent == VisualIntent.TITLE_COVER:
            for i, m in meta_map.items():
                if "cover" in m.name.lower() or "title" in m.name.lower(): return i
            return 0
        if bp.visual_intent == VisualIntent.THANK_YOU:
            for i, m in meta_map.items():
                if "thank" in m.name.lower(): return i
            return len(meta_map) - 1
        return 2 if 2 < len(meta_map) else 0 # Favoring Blank/Content Master

    def _fill_native_placeholders(self, slide, bp: SlideBlueprint):
        """Utilize the actual placeholders present in the Master Layout."""
        is_cover = bp.visual_intent == VisualIntent.TITLE_COVER
        
        # Determine content source (Mocking for now, could come from document)
        source_text = bp.meta.get("source", "Spectral Weaver Insights | Generated by Local AI")

        for ph in slide.placeholders:
            name = ph.name.lower()
            pl_type = ph.placeholder_format.type
            
            # 1. Title Placeholder
            if pl_type in (PP_PLACEHOLDER.TITLE, PP_PLACEHOLDER.CENTER_TITLE):
                ph.text = bp.title
                for p in ph.text_frame.paragraphs:
                    p.font.size = Pt(FS_TITLE_COVER if is_cover else FS_TITLE_SLIDE)
                    p.font.bold = True
                    p.font.color.rgb = self._dark()
            
            # 2. Subtitle / Summary Placeholder
            elif is_cover and (pl_type == PP_PLACEHOLDER.SUBTITLE or "sub" in name):
                ph.text = bp.summary
                for p in ph.text_frame.paragraphs: p.font.size = Pt(FS_SUB_COVER)
            
            # 3. Source / Footer Detection (By position/name)
            elif "source" in name or "footer" in name or ph.top > SH * 0.9:
                if ph.has_text_frame:
                    ph.text = source_text
                    for p in ph.text_frame.paragraphs:
                        p.font.size = Pt(8)
                        p.font.color.rgb = self._muted()
            
            # Clear others to keep it clean
            elif ph.has_text_frame:
                ph.text = ""

    def _add_footer_branding(self, slide):
        """Add a small icon/symbol to the bottom right footer area."""
        icon_size = int(Inches(0.4))
        x = int(SW - icon_size - Inches(0.4))
        y = int(SH - icon_size - Inches(0.4))
        
        # Draw a small tech symbol (Diamond)
        shp = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.DIAMOND, x, y, icon_size, icon_size)
        shp.fill.solid()
        shp.fill.fore_color.rgb = self._accent(0)
        shp.line.width = Pt(0)

    def _render_dynamic_alternating_layout(self, slide, bp: SlideBlueprint, idx: int, total: int):
        if bp.visual_intent in (VisualIntent.THANK_YOU, VisualIntent.TITLE_COVER):
            return

        margin = int(Inches(self._slide_margin))
        card_w, card_h = int(SW * 0.54), int(SH * 0.70)
        image_w = int(SW * 0.38)
        top_y = int(Inches(1.2)) # Adjusted down for title bar
        
        is_even = ((idx + 1) % 2 == 0)
        card_bg = self._light_accent(idx) 
        accent_line = self._accent(idx)
        text_color = self._get_high_contrast_color(card_bg, self._dark())
        
        if is_even:
            card_x, image_x = margin, SW - margin - image_w
        else:
            card_x, image_x = SW - margin - card_w, margin

        # Draw Geometric Content Card
        card = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, card_x, top_y, card_w, card_h)
        card.fill.solid()
        card.fill.fore_color.rgb = card_bg
        card.line.width = Pt(2.0)
        card.line.color.rgb = accent_line
        
        # Content Placement
        tm = int(Inches(0.4))
        
        if bp.visual_intent == VisualIntent.DATA_TABLE and bp.table_spec:
            self._render_table_card(slide, bp, card_x + tm, top_y + tm, card_w - 2 * tm, card_h - 2 * tm)
        elif bp.visual_intent == VisualIntent.DATA_CHART and bp.chart_spec:
            self._render_chart_card(slide, bp, card_x + tm, top_y + tm, card_w - 2 * tm, card_h - 2 * tm)
        else:
            # Standard Text Card
            body_text = "\n".join([f"\u2022 {p}" for p in bp.data_points[:6]])
            if bp.summary and len(body_text) < 150: body_text = f"{bp.summary}\n\n{body_text}"
            self._add_textbox(slide, card_x + tm, top_y + tm, card_w - 2 * tm, card_h - 2 * tm, body_text, 12, text_color)

        # Visual Accent (Premium Image)
        v_off = int(Inches(random.uniform(-0.4, 0.4)))
        asset_path = self._assets_dir / "accent.png"
        if asset_path.exists():
            self._draw_visual_accent(slide, str(asset_path), image_x, top_y + v_off, image_w, int(SH * 0.6))
        else:
            self._draw_rounded_card(slide, image_x, top_y + v_off, int(Inches(2)), int(Inches(2)), accent_line)

    def _render_table_card(self, slide, bp: SlideBlueprint, x, y, w, h):
        """Render a native PPT table inside the card area."""
        data = bp.table_spec
        rows, cols = len(data["rows"]) + 1, len(data["headers"])
        tbl_shp = slide.shapes.add_table(rows, cols, x, y, w, h)
        table = tbl_shp.table
        
        # Headers
        for i, h_text in enumerate(data["headers"]):
            cell = table.cell(0, i)
            cell.text = str(h_text)
            cell.fill.solid()
            cell.fill.fore_color.rgb = self._accent(0)
            for p in cell.text_frame.paragraphs:
                p.font.size = Pt(10)
                p.font.bold = True
                p.font.color.rgb = RGBColor(255, 255, 255)
        
        # Rows
        for r_idx, row in enumerate(data["rows"]):
            for c_idx, val in enumerate(row):
                if c_idx >= cols: break
                cell = table.cell(r_idx + 1, c_idx)
                cell.text = str(val)
                for p in cell.text_frame.paragraphs:
                    p.font.size = Pt(9)
                    p.font.color.rgb = self._dark()

    def _render_chart_card(self, slide, bp: SlideBlueprint, x, y, w, h):
        """Render a native PPT chart inside the card area."""
        chart_data = CategoryChartData()
        data = bp.chart_spec # Expected list of [label, value]
        if not data: return
        
        labels = [d[0] for d in data]
        values = [d[1] for d in data]
        chart_data.categories = labels
        chart_data.add_series("Series 1", values)
        
        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, w, h, chart_data
        ).chart
        
        chart.has_legend = False
        chart.value_axis.tick_labels.font.size = Pt(8)
        chart.category_axis.tick_labels.font.size = Pt(8)

    def _draw_visual_accent(self, slide, img_path: str, x, y, w, h):
        try:
            from PIL import Image
            with Image.open(img_path) as img:
                iw, ih = img.size
            dw = w
            dh = int(w * ih / iw)
            if dh > h:
                dh = h
                dw = int(h * iw / ih)
            slide.shapes.add_picture(img_path, int(x + (w - dw) // 2), int(y + (h - dh) // 2), dw, dh)
        except Exception as e: logger.warning(f"Visual accent failed: {e}")

    def _get_high_contrast_color(self, bg_color: RGBColor | None, fallback: RGBColor) -> RGBColor:
        if bg_color is None: return fallback
        brightness = (bg_color[0] * 299 + bg_color[1] * 587 + bg_color[2] * 114) / 1000
        return RGBColor(255, 255, 255) if brightness < 128 else RGBColor(0, 0, 0)

    def _add_textbox(self, slide, l, t, w, h, text, size, color, bold=False, align=PP_ALIGN.LEFT):
        tx = slide.shapes.add_textbox(l, t, w, h)
        tf = tx.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(size)
        p.font.bold = bold
        p.font.color.rgb = color
        p.alignment = align

    def _draw_rounded_card(self, slide, x, y, w, h, color):
        shape = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, x, y, w, h)
        shape.fill.solid()
        shape.fill.fore_color.rgb = color
        shape.line.width = Pt(0)

    def _primary(self): return RGBColor(*self.theme.primary_color)
    def _accent(self, i): return RGBColor(*self.theme.accent_colors[i % len(self.theme.accent_colors)])
    def _light_accent(self, i): return RGBColor(*self.theme.light_colors[i % len(self.theme.light_colors)])
    def _muted(self): return RGBColor(*self.theme.muted_color)
    def _dark(self): return RGBColor(*self.theme.dark_color)
